// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHS6lvlefdD5JOOPpRJdcsQWNXE7cNjo0',
    appId: '1:64774920908:web:389ff9ce01c3533c1b8069',
    messagingSenderId: '64774920908',
    projectId: 'chat-app-c67bd',
    authDomain: 'chat-app-c67bd.firebaseapp.com',
    storageBucket: 'chat-app-c67bd.appspot.com',
    measurementId: 'G-HKMBYVM8B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyiK5YxXa3J61-xrk0pP8w5JW17n41LPI',
    appId: '1:64774920908:android:0c0df8916d290dcc1b8069',
    messagingSenderId: '64774920908',
    projectId: 'chat-app-c67bd',
    storageBucket: 'chat-app-c67bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOp7aWziYfqkIvi5D3MnFjIjw9j_gl7aI',
    appId: '1:64774920908:ios:1fe43ae0b8bf5b041b8069',
    messagingSenderId: '64774920908',
    projectId: 'chat-app-c67bd',
    storageBucket: 'chat-app-c67bd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOp7aWziYfqkIvi5D3MnFjIjw9j_gl7aI',
    appId: '1:64774920908:ios:1fe43ae0b8bf5b041b8069',
    messagingSenderId: '64774920908',
    projectId: 'chat-app-c67bd',
    storageBucket: 'chat-app-c67bd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
